version: "3"
services:
  website:
    build: ./website
    ports:
      - 8085:80
    restart: always
    depends_on:
      - api
    networks:
      - mlnetwork
  api:
    build: ./api
    ports:
      - 8086:80
    restart: always
    networks:
      - mlnetwork
    volumes:
      - "./api:/code"
      - "./db:/code/db"
networks:
  mlnetwork:
    driver: bridge