version: "3"
services:
  website:
    build: ./website
    ports:
      - 8085:80
    restart: always
    networks:
      - mynetwork
  api:
    build: ./api
    ports:
      - 8086:80
    restart: always
    networks:
      - mynetwork
    volumes:
      - ./api:/code
networks:
  mynetwork:
    driver: bridge